export const ACTIVITIES_EMOJIS = [
  { char: '⚽', name: 'soccer ball sport', cat: 'Activities' },
  { char: '🏀', name: 'basketball sport', cat: 'Activities' },
  { char: '🏈', name: 'american football sport', cat: 'Activities' },
  { char: '⚾', name: 'baseball sport', cat: 'Activities' },
  { char: '🥎', name: 'softball sport', cat: 'Activities' },
  { char: '🎾', name: 'tennis ball sport', cat: 'Activities' },
  { char: '🏐', name: 'volleyball sport', cat: 'Activities' },
  { char: '🏉', name: 'rugby football sport', cat: 'Activities' },
  { char: '🥏', name: 'flying disc sport', cat: 'Activities' },
  { char: '🎱', name: 'pool ball 8 ball sport', cat: 'Activities' },
  { char: '🪀', name: 'yo-yo toy', cat: 'Activities' },
  { char: '🏓', name: 'ping pong table tennis sport', cat: 'Activities' },
  { char: '🏸', name: 'badminton sport', cat: 'Activities' },
  { char: '🏒', name: 'ice hockey sport', cat: 'Activities' },
  { char: '🏑', name: 'field hockey sport', cat: 'Activities' },
  { char: '🥍', name: 'lacrosse sport', cat: 'Activities' },
  { char: '🏏', name: 'cricket bat and ball sport', cat: 'Activities' },
  { char: '🪃', name: 'boomerang', cat: 'Activities' },
  { char: '🥅', name: 'goal net sport', cat: 'Activities' },
  { char: '⛳', name: 'flag in hole golf sport', cat: 'Activities' },
  { char: '🪁', name: 'kite toy', cat: 'Activities' },
  { char: '🏹', name: 'bow and arrow sport', cat: 'Activities' },
  { char: '🤿', name: 'diving mask sport', cat: 'Activities' },
  { char: '🥊', name: 'boxing glove sport', cat: 'Activities' },
  { char: '🥋', name: 'martial arts uniform sport', cat: 'Activities' },
  { char: '🎽', name: 'running shirt sport', cat: 'Activities' },
  { char: '🛹', name: 'skateboard sport', cat: 'Activities' },
  { char: '🛷', name: 'sled sport', cat: 'Activities' },
  { char: '⛸️', name: 'ice skate sport', cat: 'Activities' },
  { char: '🥌', name: 'curling stone sport', cat: 'Activities' },
  { char: '🎿', name: 'skis sport', cat: 'Activities' },
  { char: '⛷️', name: 'skier sport', cat: 'Activities' },
  { char: '🏂', name: 'snowboarder sport', cat: 'Activities' },
  { char: '🪂', name: 'parachute sport', cat: 'Activities' },
  { char: '🏋️', name: 'person lifting weights sport', cat: 'Activities' },
  { char: '🤼', name: 'people wrestling sport', cat: 'Activities' },
  { char: '🤸', name: 'person cartwheeling sport', cat: 'Activities' },
  { char: '⛹️', name: 'person bouncing ball sport', cat: 'Activities' },
  { char: '🤺', name: 'person fencing sport', cat: 'Activities' },
  { char: '🤾', name: 'person playing handball sport', cat: 'Activities' },
  { char: '🏌️', name: 'person golfing sport', cat: 'Activities' },
  { char: '🏇', name: 'horse racing sport', cat: 'Activities' },
  { char: '🧘', name: 'person in lotus position yoga', cat: 'Activities' },
  { char: '🏄', name: 'person surfing sport', cat: 'Activities' },
  { char: '🏊', name: 'person swimming sport', cat: 'Activities' },
  { char: '🤽', name: 'person playing water polo sport', cat: 'Activities' },
  { char: '🚣', name: 'person rowing boat sport', cat: 'Activities' },
  { char: '🧗', name: 'person climbing sport', cat: 'Activities' },
  { char: '🚵', name: 'person mountain biking sport', cat: 'Activities' },
  { char: '🚴', name: 'person biking sport', cat: 'Activities' },
  { char: '🏆', name: 'trophy win', cat: 'Activities' },
  { char: '🥇', name: '1st place medal win', cat: 'Activities' },
  { char: '🥈', name: '2nd place medal win', cat: 'Activities' },
  { char: '🥉', name: '3rd place medal win', cat: 'Activities' },
  { char: '🏅', name: 'sports medal win', cat: 'Activities' },
  { char: '🎖️', name: 'military medal win', cat: 'Activities' },
  { char: '🏵️', name: 'rosette win', cat: 'Activities' },
  { char: '🎗️', name: 'reminder ribbon win', cat: 'Activities' },
  { char: '🎫', name: 'ticket', cat: 'Activities' },
  { char: '🎟️', name: 'admission tickets', cat: 'Activities' },
  { char: '🎭', name: 'performing arts theater', cat: 'Activities' },
  { char: '🎨', name: 'artist palette paint', cat: 'Activities' },
  { char: '🎬', name: 'clapper board movie', cat: 'Activities' },
  { char: '🎤', name: 'microphone sing', cat: 'Activities' },
  { char: '🎧', name: 'headphone music', cat: 'Activities' },
  { char: '🎼', name: 'musical score music', cat: 'Activities' },
  { char: '🎹', name: 'musical keyboard piano music', cat: 'Activities' },
  { char: '🥁', name: 'drum music', cat: 'Activities' },
  { char: '🎷', name: 'saxophone music', cat: 'Activities' },
  { char: '🎺', name: 'trumpet music', cat: 'Activities' },
  { char: '🎸', name: 'guitar music', cat: 'Activities' },
  { char: '🪕', name: 'banjo music', cat: 'Activities' },
  { char: '🎻', name: 'violin music', cat: 'Activities' },
  { char: '🎲', name: 'game die play', cat: 'Activities' },
  { char: '🧩', name: 'puzzle piece play', cat: 'Activities' },
  { char: '♟️', name: 'chess pawn play', cat: 'Activities' },
  { char: '🎯', name: 'direct hit dart sport', cat: 'Activities' },
  { char: '🎳', name: 'bowling sport', cat: 'Activities' },
  { char: '🎮', name: 'video game controller play', cat: 'Activities' },
  { char: '🎰', name: 'slot machine play', cat: 'Activities' }
];
