export const ANIMALS_EMOJIS = [
  { char: '🐶', name: 'dog face animal', cat: 'Animals & Nature' },
  { char: '🐱', name: 'cat face animal', cat: 'Animals & Nature' },
  { char: '🐭', name: 'mouse face animal', cat: 'Animals & Nature' },
  { char: '🐹', name: 'hamster face animal', cat: 'Animals & Nature' },
  { char: '🐰', name: 'rabbit face animal', cat: 'Animals & Nature' },
  { char: '🦊', name: 'fox face animal', cat: 'Animals & Nature' },
  { char: '🐻', name: 'bear face animal', cat: 'Animals & Nature' },
  { char: '🐼', name: 'panda face animal', cat: 'Animals & Nature' },
  { char: '🐨', name: 'koala face animal', cat: 'Animals & Nature' },
  { char: '🐯', name: 'tiger face animal', cat: 'Animals & Nature' },
  { char: '🦁', name: 'lion face animal', cat: 'Animals & Nature' },
  { char: '🐮', name: 'cow face animal', cat: 'Animals & Nature' },
  { char: '🐷', name: 'pig face animal', cat: 'Animals & Nature' },
  { char: '🐽', name: 'pig nose animal', cat: 'Animals & Nature' },
  { char: '🐸', name: 'frog face animal', cat: 'Animals & Nature' },
  { char: '🐵', name: 'monkey face animal', cat: 'Animals & Nature' },
  { char: '🙈', name: 'see no evil monkey', cat: 'Animals & Nature' },
  { char: '🙉', name: 'hear no evil monkey', cat: 'Animals & Nature' },
  { char: '🙊', name: 'speak no evil monkey', cat: 'Animals & Nature' },
  { char: '🐒', name: 'monkey animal', cat: 'Animals & Nature' },
  { char: '🦍', name: 'gorilla animal', cat: 'Animals & Nature' },
  { char: '🦧', name: 'orangutan animal', cat: 'Animals & Nature' },
  { char: '🐶', name: 'dog animal', cat: 'Animals & Nature' },
  { char: '🐕', name: 'dog animal', cat: 'Animals & Nature' },
  { char: '🦮', name: 'guide dog animal', cat: 'Animals & Nature' },
  { char: '🐩', name: 'poodle dog animal', cat: 'Animals & Nature' },
  { char: '🐺', name: 'wolf animal', cat: 'Animals & Nature' },
  { char: '🦊', name: 'fox animal', cat: 'Animals & Nature' },
  { char: '🦝', name: 'raccoon animal', cat: 'Animals & Nature' },
  { char: '🐱', name: 'cat animal', cat: 'Animals & Nature' },
  { char: '🐈', name: 'cat animal', cat: 'Animals & Nature' },
  { char: '🦁', name: 'lion animal', cat: 'Animals & Nature' },
  { char: '🐯', name: 'tiger animal', cat: 'Animals & Nature' },
  { char: '🐅', name: 'tiger animal', cat: 'Animals & Nature' },
  { char: '🐆', name: 'leopard animal', cat: 'Animals & Nature' },
  { char: '🐴', name: 'horse face animal', cat: 'Animals & Nature' },
  { char: '🐎', name: 'horse animal', cat: 'Animals & Nature' },
  { char: '🦄', name: 'unicorn animal', cat: 'Animals & Nature' },
  { char: '🦓', name: 'zebra animal', cat: 'Animals & Nature' },
  { char: '🦌', name: 'deer animal', cat: 'Animals & Nature' },
  { char: '🦬', name: 'bison animal', cat: 'Animals & Nature' },
  { char: '🐮', name: 'cow face animal', cat: 'Animals & Nature' },
  { char: '🐂', name: 'ox animal', cat: 'Animals & Nature' },
  { char: '🐃', name: 'water buffalo animal', cat: 'Animals & Nature' },
  { char: '🐄', name: 'cow animal', cat: 'Animals & Nature' },
  { char: '🐷', name: 'pig face animal', cat: 'Animals & Nature' },
  { char: '🐖', name: 'pig animal', cat: 'Animals & Nature' },
  { char: '🐗', name: 'boar animal', cat: 'Animals & Nature' },
  { char: '🐽', name: 'pig nose animal', cat: 'Animals & Nature' },
  { char: '🐏', name: 'ram animal', cat: 'Animals & Nature' },
  { char: '🐑', name: 'ewe sheep animal', cat: 'Animals & Nature' },
  { char: '🐐', name: 'goat animal', cat: 'Animals & Nature' },
  { char: '🐪', name: 'camel animal', cat: 'Animals & Nature' },
  { char: '🐫', name: 'two hump camel animal', cat: 'Animals & Nature' },
  { char: '🦙', name: 'llama animal', cat: 'Animals & Nature' },
  { char: '🦒', name: 'giraffe animal', cat: 'Animals & Nature' },
  { char: '🐘', name: 'elephant animal', cat: 'Animals & Nature' },
  { char: '🦣', name: 'mammoth animal', cat: 'Animals & Nature' },
  { char: '🦏', name: 'rhinoceros animal', cat: 'Animals & Nature' },
  { char: '🦛', name: 'hippopotamus animal', cat: 'Animals & Nature' },
  { char: '🐭', name: 'mouse face animal', cat: 'Animals & Nature' },
  { char: '🐁', name: 'mouse animal', cat: 'Animals & Nature' },
  { char: '🐀', name: 'rat animal', cat: 'Animals & Nature' },
  { char: '🐹', name: 'hamster face animal', cat: 'Animals & Nature' },
  { char: '🐰', name: 'rabbit face animal', cat: 'Animals & Nature' },
  { char: '🐇', name: 'rabbit animal', cat: 'Animals & Nature' },
  { char: '🐿️', name: 'chipmunk animal', cat: 'Animals & Nature' },
  { char: '🦫', name: 'beaver animal', cat: 'Animals & Nature' },
  { char: '🦔', name: 'hedgehog animal', cat: 'Animals & Nature' },
  { char: '🦇', name: 'bat animal', cat: 'Animals & Nature' },
  { char: '🐻', name: 'bear animal', cat: 'Animals & Nature' },
  { char: '🐨', name: 'koala animal', cat: 'Animals & Nature' },
  { char: '🐼', name: 'panda animal', cat: 'Animals & Nature' },
  { char: '🦥', name: 'sloth animal', cat: 'Animals & Nature' },
  { char: '🦦', name: 'otter animal', cat: 'Animals & Nature' },
  { char: '🦨', name: 'skunk animal', cat: 'Animals & Nature' },
  { char: '🦘', name: 'kangaroo animal', cat: 'Animals & Nature' },
  { char: '🦡', name: 'badger animal', cat: 'Animals & Nature' },
  { char: '🐾', name: 'paw prints animal', cat: 'Animals & Nature' },
  { char: '🦃', name: 'turkey animal', cat: 'Animals & Nature' },
  { char: '🐔', name: 'chicken animal', cat: 'Animals & Nature' },
  { char: '🐓', name: 'rooster animal', cat: 'Animals & Nature' },
  { char: '🐣', name: 'hatching chick animal', cat: 'Animals & Nature' },
  { char: '🐤', name: 'baby chick animal', cat: 'Animals & Nature' },
  { char: '🐥', name: 'front facing baby chick animal', cat: 'Animals & Nature' },
  { char: '🐦', name: 'bird animal', cat: 'Animals & Nature' },
  { char: '🐧', name: 'penguin animal', cat: 'Animals & Nature' },
  { char: '🕊️', name: 'dove peace bird animal', cat: 'Animals & Nature' },
  { char: '🦅', name: 'eagle animal', cat: 'Animals & Nature' },
  { char: '🦆', name: 'duck animal', cat: 'Animals & Nature' },
  { char: '🦢', name: 'swan animal', cat: 'Animals & Nature' },
  { char: '🦉', name: 'owl animal', cat: 'Animals & Nature' },
  { char: '🦤', name: 'dodo animal', cat: 'Animals & Nature' },
  { char: '🦩', name: 'flamingo animal', cat: 'Animals & Nature' },
  { char: '🦚', name: 'peacock animal', cat: 'Animals & Nature' },
  { char: '🦜', name: 'parrot animal', cat: 'Animals & Nature' },
  { char: '🐸', name: 'frog animal', cat: 'Animals & Nature' },
  { char: '🐊', name: 'crocodile animal', cat: 'Animals & Nature' },
  { char: '🐢', name: 'turtle animal', cat: 'Animals & Nature' },
  { char: '🦎', name: 'lizard animal', cat: 'Animals & Nature' },
  { char: '🐍', name: 'snake animal', cat: 'Animals & Nature' },
  { char: '🐲', name: 'dragon face animal', cat: 'Animals & Nature' },
  { char: '🐉', name: 'dragon animal', cat: 'Animals & Nature' },
  { char: '🦕', name: 'sauropod dinosaur animal', cat: 'Animals & Nature' },
  { char: '🦖', name: 't-rex dinosaur animal', cat: 'Animals & Nature' },
  { char: '🐳', name: 'spouting whale animal', cat: 'Animals & Nature' },
  { char: '🐋', name: 'whale animal', cat: 'Animals & Nature' },
  { char: '🐬', name: 'dolphin animal', cat: 'Animals & Nature' },
  { char: '🦭', name: 'seal animal', cat: 'Animals & Nature' },
  { char: '🐟', name: 'fish animal', cat: 'Animals & Nature' },
  { char: '🐠', name: 'tropical fish animal', cat: 'Animals & Nature' },
  { char: '🐡', name: 'blowfish animal', cat: 'Animals & Nature' },
  { char: '🦈', name: 'shark animal', cat: 'Animals & Nature' },
  { char: '🐙', name: 'octopus animal', cat: 'Animals & Nature' },
  { char: '🐚', name: 'spiral shell animal', cat: 'Animals & Nature' },
  { char: '🐌', name: 'snail animal', cat: 'Animals & Nature' },
  { char: '🦋', name: 'butterfly animal', cat: 'Animals & Nature' },
  { char: '🐛', name: 'bug animal', cat: 'Animals & Nature' },
  { char: '🐜', name: 'ant animal', cat: 'Animals & Nature' },
  { char: '🐝', name: 'honeybee animal', cat: 'Animals & Nature' },
  { char: '🪲', name: 'beetle animal', cat: 'Animals & Nature' },
  { char: '🐞', name: 'lady beetle animal', cat: 'Animals & Nature' },
  { char: '🦗', name: 'cricket animal', cat: 'Animals & Nature' },
  { char: '🪳', name: 'cockroach animal', cat: 'Animals & Nature' },
  { char: '🕷️', name: 'spider animal', cat: 'Animals & Nature' },
  { char: '🕸️', name: 'spider web animal', cat: 'Animals & Nature' },
  { char: '🦂', name: 'scorpion animal', cat: 'Animals & Nature' },
  { char: '🦟', name: 'mosquito animal', cat: 'Animals & Nature' },
  { char: '🪱', name: 'worm animal', cat: 'Animals & Nature' },
  { char: '🦠', name: 'microbe animal', cat: 'Animals & Nature' },
  { char: '💐', name: 'bouquet flower', cat: 'Animals & Nature' },
  { char: '🌸', name: 'cherry blossom flower', cat: 'Animals & Nature' },
  { char: '💮', name: 'white flower', cat: 'Animals & Nature' },
  { char: '🏵️', name: 'rosette flower', cat: 'Animals & Nature' },
  { char: '🌹', name: 'rose flower', cat: 'Animals & Nature' },
  { char: '🥀', name: 'wilted flower', cat: 'Animals & Nature' },
  { char: '🌺', name: 'hibiscus flower', cat: 'Animals & Nature' },
  { char: '🌻', name: 'sunflower flower', cat: 'Animals & Nature' },
  { char: '🌼', name: 'blossom flower', cat: 'Animals & Nature' },
  { char: '🌷', name: 'tulip flower', cat: 'Animals & Nature' },
  { char: '🌱', name: 'seedling nature', cat: 'Animals & Nature' },
  { char: '🪴', name: 'potted plant nature', cat: 'Animals & Nature' },
  { char: '🌲', name: 'evergreen tree nature', cat: 'Animals & Nature' },
  { char: '🌳', name: 'deciduous tree nature', cat: 'Animals & Nature' },
  { char: '🌴', name: 'palm tree nature', cat: 'Animals & Nature' },
  { char: '🌵', name: 'cactus nature', cat: 'Animals & Nature' },
  { char: '🌾', name: 'sheaf of rice nature', cat: 'Animals & Nature' },
  { char: '🌿', name: 'herb nature', cat: 'Animals & Nature' },
  { char: '☘️', name: 'shamrock nature', cat: 'Animals & Nature' },
  { char: '🍀', name: 'four leaf clover nature lucky', cat: 'Animals & Nature' },
  { char: '🍁', name: 'maple leaf nature', cat: 'Animals & Nature' },
  { char: '🍂', name: 'fallen leaf nature', cat: 'Animals & Nature' },
  { char: '🍃', name: 'leaf fluttering in wind nature', cat: 'Animals & Nature' }
];
