export const FOOD_EMOJIS = [
  { char: '🍏', name: 'green apple fruit food', cat: 'Food & Drink' },
  { char: '🍎', name: 'red apple fruit food', cat: 'Food & Drink' },
  { char: '🍐', name: 'pear fruit food', cat: 'Food & Drink' },
  { char: '🍊', name: 'tangerine orange fruit food', cat: 'Food & Drink' },
  { char: '🍋', name: 'lemon fruit food', cat: 'Food & Drink' },
  { char: '🍌', name: 'banana fruit food', cat: 'Food & Drink' },
  { char: '🍉', name: 'watermelon fruit food', cat: 'Food & Drink' },
  { char: '🍇', name: 'grapes fruit food', cat: 'Food & Drink' },
  { char: '🍓', name: 'strawberry fruit food', cat: 'Food & Drink' },
  { char: '🫐', name: 'blueberries fruit food', cat: 'Food & Drink' },
  { char: '🍈', name: 'melon fruit food', cat: 'Food & Drink' },
  { char: '🍒', name: 'cherries fruit food', cat: 'Food & Drink' },
  { char: '🍑', name: 'peach fruit food', cat: 'Food & Drink' },
  { char: '🥭', name: 'mango fruit food', cat: 'Food & Drink' },
  { char: '🍍', name: 'pineapple fruit food', cat: 'Food & Drink' },
  { char: '🥥', name: 'coconut fruit food', cat: 'Food & Drink' },
  { char: '🥝', name: 'kiwi fruit food', cat: 'Food & Drink' },
  { char: '🍅', name: 'tomato vegetable food', cat: 'Food & Drink' },
  { char: '🍆', name: 'eggplant vegetable food', cat: 'Food & Drink' },
  { char: '🥑', name: 'avocado vegetable food', cat: 'Food & Drink' },
  { char: '🥦', name: 'broccoli vegetable food', cat: 'Food & Drink' },
  { char: '🥬', name: 'leafy green vegetable food', cat: 'Food & Drink' },
  { char: '🥒', name: 'cucumber vegetable food', cat: 'Food & Drink' },
  { char: '🌶️', name: 'hot pepper vegetable food spicy', cat: 'Food & Drink' },
  { char: '🫑', name: 'bell pepper vegetable food', cat: 'Food & Drink' },
  { char: '🌽', name: 'corn vegetable food', cat: 'Food & Drink' },
  { char: '🥕', name: 'carrot vegetable food', cat: 'Food & Drink' },
  { char: '🧄', name: 'garlic vegetable food', cat: 'Food & Drink' },
  { char: '🧅', name: 'onion vegetable food', cat: 'Food & Drink' },
  { char: '🍄', name: 'mushroom vegetable food', cat: 'Food & Drink' },
  { char: '🥜', name: 'peanuts food', cat: 'Food & Drink' },
  { char: '🌰', name: 'chestnut food', cat: 'Food & Drink' },
  { char: '🍞', name: 'bread food', cat: 'Food & Drink' },
  { char: '🥐', name: 'croissant food', cat: 'Food & Drink' },
  { char: '🥖', name: 'baguette bread food', cat: 'Food & Drink' },
  { char: '🫓', name: 'flatbread food', cat: 'Food & Drink' },
  { char: '🥨', name: 'pretzel food', cat: 'Food & Drink' },
  { char: '🥯', name: 'bagel food', cat: 'Food & Drink' },
  { char: '🥞', name: 'pancakes food', cat: 'Food & Drink' },
  { char: '🧇', name: 'waffle food', cat: 'Food & Drink' },
  { char: '🧀', name: 'cheese wedge food', cat: 'Food & Drink' },
  { char: '🍖', name: 'meat on bone food', cat: 'Food & Drink' },
  { char: '🍗', name: 'poultry leg chicken food', cat: 'Food & Drink' },
  { char: '🥩', name: 'cut of meat food', cat: 'Food & Drink' },
  { char: '🥓', name: 'bacon food', cat: 'Food & Drink' },
  { char: '🍔', name: 'hamburger burger food', cat: 'Food & Drink' },
  { char: '🍟', name: 'french fries food', cat: 'Food & Drink' },
  { char: '🍕', name: 'pizza slice food', cat: 'Food & Drink' },
  { char: '🌭', name: 'hot dog food', cat: 'Food & Drink' },
  { char: '🥪', name: 'sandwich food', cat: 'Food & Drink' },
  { char: '🌮', name: 'taco food', cat: 'Food & Drink' },
  { char: '🌯', name: 'burrito food', cat: 'Food & Drink' },
  { char: '🫔', name: 'tamale food', cat: 'Food & Drink' },
  { char: '🥙', name: 'stuffed flatbread food', cat: 'Food & Drink' },
  { char: '🧆', name: 'falafel food', cat: 'Food & Drink' },
  { char: '🥚', name: 'egg food', cat: 'Food & Drink' },
  { char: '🍳', name: 'cooking egg breakfast food', cat: 'Food & Drink' },
  { char: '🥘', name: 'shallow pan of food', cat: 'Food & Drink' },
  { char: '🍲', name: 'pot of food stew', cat: 'Food & Drink' },
  { char: '🥣', name: 'bowl with spoon food', cat: 'Food & Drink' },
  { char: '🥗', name: 'green salad food', cat: 'Food & Drink' },
  { char: '🍿', name: 'popcorn food', cat: 'Food & Drink' },
  { char: '🧈', name: 'butter food', cat: 'Food & Drink' },
  { char: '🧂', name: 'salt food', cat: 'Food & Drink' },
  { char: '🥫', name: 'canned food', cat: 'Food & Drink' },
  { char: '🍱', name: 'bento box food', cat: 'Food & Drink' },
  { char: '🍘', name: 'rice cracker food', cat: 'Food & Drink' },
  { char: '🍙', name: 'rice ball food', cat: 'Food & Drink' },
  { char: '🍚', name: 'cooked rice food', cat: 'Food & Drink' },
  { char: '🍛', name: 'curry rice food', cat: 'Food & Drink' },
  { char: '🍜', name: 'steaming bowl ramen noodles food', cat: 'Food & Drink' },
  { char: '🍝', name: 'spaghetti food', cat: 'Food & Drink' },
  { char: '🍠', name: 'roasted sweet potato food', cat: 'Food & Drink' },
  { char: '🍢', name: 'oden food', cat: 'Food & Drink' },
  { char: '🍣', name: 'sushi food', cat: 'Food & Drink' },
  { char: '🍤', name: 'fried shrimp food', cat: 'Food & Drink' },
  { char: '🍥', name: 'fish cake with swirl food', cat: 'Food & Drink' },
  { char: '🥮', name: 'moon cake food', cat: 'Food & Drink' },
  { char: '🍡', name: 'dango food', cat: 'Food & Drink' },
  { char: '🥟', name: 'dumpling food', cat: 'Food & Drink' },
  { char: '🥠', name: 'fortune cookie food', cat: 'Food & Drink' },
  { char: '🥡', name: 'takeout box food', cat: 'Food & Drink' },
  { char: '🦀', name: 'crab animal food', cat: 'Food & Drink' },
  { char: '🦞', name: 'lobster animal food', cat: 'Food & Drink' },
  { char: '🦐', name: 'shrimp animal food', cat: 'Food & Drink' },
  { char: '🦑', name: 'squid animal food', cat: 'Food & Drink' },
  { char: '🦪', name: 'oyster animal food', cat: 'Food & Drink' },
  { char: '🍦', name: 'soft serve ice cream food', cat: 'Food & Drink' },
  { char: '🍧', name: 'shaved ice food', cat: 'Food & Drink' },
  { char: '🍨', name: 'ice cream food', cat: 'Food & Drink' },
  { char: '🍩', name: 'doughnut food', cat: 'Food & Drink' },
  { char: '🍪', name: 'cookie food', cat: 'Food & Drink' },
  { char: '🎂', name: 'birthday cake food', cat: 'Food & Drink' },
  { char: '🍰', name: 'shortcake food', cat: 'Food & Drink' },
  { char: '🧁', name: 'cupcake food', cat: 'Food & Drink' },
  { char: '🥧', name: 'pie food', cat: 'Food & Drink' },
  { char: '🍫', name: 'chocolate bar food', cat: 'Food & Drink' },
  { char: '🍬', name: 'candy food', cat: 'Food & Drink' },
  { char: '🍭', name: 'lollipop food', cat: 'Food & Drink' },
  { char: '🍮', name: 'custard food', cat: 'Food & Drink' },
  { char: '🍯', name: 'honey pot food', cat: 'Food & Drink' },
  { char: '🍼', name: 'baby bottle drink', cat: 'Food & Drink' },
  { char: '🥛', name: 'glass of milk drink', cat: 'Food & Drink' },
  { char: '☕', name: 'hot beverage coffee tea drink', cat: 'Food & Drink' },
  { char: '🫖', name: 'teapot drink', cat: 'Food & Drink' },
  { char: '🍵', name: 'teacup without handle drink', cat: 'Food & Drink' },
  { char: '🍶', name: 'sake drink', cat: 'Food & Drink' },
  { char: '🍾', name: 'bottle with popping cork drink alcohol champagne', cat: 'Food & Drink' },
  { char: '🍷', name: 'wine glass drink alcohol', cat: 'Food & Drink' },
  { char: '🍸', name: 'cocktail glass drink alcohol', cat: 'Food & Drink' },
  { char: '🍹', name: 'tropical drink alcohol', cat: 'Food & Drink' },
  { char: '🍺', name: 'beer mug drink alcohol', cat: 'Food & Drink' },
  { char: '🍻', name: 'clinking beer mugs drink alcohol', cat: 'Food & Drink' },
  { char: '🥂', name: 'clinking glasses drink alcohol', cat: 'Food & Drink' },
  { char: '🥃', name: 'tumbler glass drink alcohol', cat: 'Food & Drink' },
  { char: '🥤', name: 'cup with straw drink', cat: 'Food & Drink' },
  { char: '🧋', name: 'bubble tea drink', cat: 'Food & Drink' },
  { char: '🧃', name: 'beverage box drink', cat: 'Food & Drink' },
  { char: '🧉', name: 'mate drink', cat: 'Food & Drink' },
  { char: '🧊', name: 'ice cube', cat: 'Food & Drink' },
  { char: '🥢', name: 'chopsticks', cat: 'Food & Drink' },
  { char: '🍽️', name: 'fork and knife with plate', cat: 'Food & Drink' },
  { char: '🍴', name: 'fork and knife', cat: 'Food & Drink' },
  { char: '🥄', name: 'spoon', cat: 'Food & Drink' },
  { char: '🔪', name: 'kitchen knife', cat: 'Food & Drink' },
  { char: '🏺', name: 'amphora', cat: 'Food & Drink' }
];
