export const SMILEYS_EMOJIS = [
  { char: '😀', name: 'grinning face smiley happy', cat: 'Smileys & People' },
  { char: '😃', name: 'grinning face big eyes smiley happy', cat: 'Smileys & People' },
  { char: '😄', name: 'grinning face squinting eyes smiley happy', cat: 'Smileys & People' },
  { char: '😁', name: 'beaming face smiley happy', cat: 'Smileys & People' },
  { char: '😆', name: 'grinning squinting face smiley happy', cat: 'Smileys & People' },
  { char: '😅', name: 'grinning face sweat smiley happy', cat: 'Smileys & People' },
  { char: '🤣', name: 'rolling on floor laughing rofl smiley happy', cat: 'Smileys & People' },
  { char: '😂', name: 'face tears joy lol smiley happy', cat: 'Smileys & People' },
  { char: '🙂', name: 'slightly smiling face happy', cat: 'Smileys & People' },
  { char: '🙃', name: 'upside down face', cat: 'Smileys & People' },
  { char: '😉', name: 'winking face wink', cat: 'Smileys & People' },
  { char: '😊', name: 'smiling face eyes happy', cat: 'Smileys & People' },
  { char: '😇', name: 'smiling face halo angel', cat: 'Smileys & People' },
  { char: '🥰', name: 'smiling face hearts love', cat: 'Smileys & People' },
  { char: '😍', name: 'smiling face heart eyes love', cat: 'Smileys & People' },
  { char: '🤩', name: 'star struck eyes', cat: 'Smileys & People' },
  { char: '😘', name: 'face blowing kiss love', cat: 'Smileys & People' },
  { char: '😗', name: 'kissing face', cat: 'Smileys & People' },
  { char: '😚', name: 'kissing face closed eyes', cat: 'Smileys & People' },
  { char: '😙', name: 'kissing face smiling eyes', cat: 'Smileys & People' },
  { char: '😋', name: 'face savoring food hungry yum', cat: 'Smileys & People' },
  { char: '😛', name: 'face tongue out', cat: 'Smileys & People' },
  { char: '😜', name: 'winking face tongue out wink', cat: 'Smileys & People' },
  { char: '🤪', name: 'zany face crazy', cat: 'Smileys & People' },
  { char: '😝', name: 'squinting face tongue out', cat: 'Smileys & People' },
  { char: '🤑', name: 'money mouth face rich', cat: 'Smileys & People' },
  { char: '🤗', name: 'hugging face hug', cat: 'Smileys & People' },
  { char: '🤭', name: 'face hand mouth', cat: 'Smileys & People' },
  { char: '🤫', name: 'shushing face quiet', cat: 'Smileys & People' },
  { char: '🤔', name: 'thinking face hmm', cat: 'Smileys & People' },
  { char: '🤐', name: 'zipper mouth face quiet', cat: 'Smileys & People' },
  { char: '🤨', name: 'face raised eyebrow', cat: 'Smileys & People' },
  { char: '😐', name: 'neutral face', cat: 'Smileys & People' },
  { char: '😑', name: 'expressionless face', cat: 'Smileys & People' },
  { char: '😶', name: 'face without mouth', cat: 'Smileys & People' },
  { char: '😏', name: 'smirking face smirk', cat: 'Smileys & People' },
  { char: '😒', name: 'unamused face bored', cat: 'Smileys & People' },
  { char: '🙄', name: 'face rolling eyes', cat: 'Smileys & People' },
  { char: '😬', name: 'grimacing face', cat: 'Smileys & People' },
  { char: '🤥', name: 'lying face pinocchio', cat: 'Smileys & People' },
  { char: '😔', name: 'pensive face sad', cat: 'Smileys & People' },
  { char: '😪', name: 'sleepy face', cat: 'Smileys & People' },
  { char: '🤤', name: 'drooling face', cat: 'Smileys & People' },
  { char: '😴', name: 'sleeping face zzz', cat: 'Smileys & People' },
  { char: '😷', name: 'face medical mask sick', cat: 'Smileys & People' },
  { char: '🤒', name: 'face thermometer sick', cat: 'Smileys & People' },
  { char: '🤕', name: 'face head bandage sick', cat: 'Smileys & People' },
  { char: '🤢', name: 'nauseated face sick puke', cat: 'Smileys & People' },
  { char: '🤮', name: 'face vomiting puke sick', cat: 'Smileys & People' },
  { char: '🤧', name: 'sneezing face sick', cat: 'Smileys & People' },
  { char: '🥵', name: 'hot face red sweat', cat: 'Smileys & People' },
  { char: '🥶', name: 'cold face blue ice', cat: 'Smileys & People' },
  { char: '🥴', name: 'woozy face dizzy', cat: 'Smileys & People' },
  { char: '😵', name: 'dizzy face', cat: 'Smileys & People' },
  { char: '🤯', name: 'exploding head mind blown', cat: 'Smileys & People' },
  { char: '🤠', name: 'cowboy hat face', cat: 'Smileys & People' },
  { char: '🥳', name: 'partying face celebrate', cat: 'Smileys & People' },
  { char: '😎', name: 'smiling face sunglasses cool', cat: 'Smileys & People' },
  { char: '🤓', name: 'nerd face', cat: 'Smileys & People' },
  { char: '🧐', name: 'face monocle', cat: 'Smileys & People' },
  { char: '😕', name: 'confused face', cat: 'Smileys & People' },
  { char: '😟', name: 'worried face', cat: 'Smileys & People' },
  { char: '🙁', name: 'slightly frowning face', cat: 'Smileys & People' },
  { char: '☹️', name: 'frowning face', cat: 'Smileys & People' },
  { char: '😮', name: 'face open mouth', cat: 'Smileys & People' },
  { char: '😯', name: 'hushed face', cat: 'Smileys & People' },
  { char: '😲', name: 'astonished face', cat: 'Smileys & People' },
  { char: '😳', name: 'flushed face', cat: 'Smileys & People' },
  { char: '🥺', name: 'pleading face puppy eyes', cat: 'Smileys & People' },
  { char: '😦', name: 'frowning face open mouth', cat: 'Smileys & People' },
  { char: '😧', name: 'anguished face', cat: 'Smileys & People' },
  { char: '😨', name: 'fearful face', cat: 'Smileys & People' },
  { char: '😰', name: 'face open mouth cold sweat', cat: 'Smileys & People' },
  { char: '😥', name: 'sad relieved face', cat: 'Smileys & People' },
  { char: '😢', name: 'crying face tear', cat: 'Smileys & People' },
  { char: '😭', name: 'loudly crying face', cat: 'Smileys & People' },
  { char: '😱', name: 'face screaming in fear', cat: 'Smileys & People' },
  { char: '😖', name: 'confounded face', cat: 'Smileys & People' },
  { char: '😣', name: 'persevering face', cat: 'Smileys & People' },
  { char: '😞', name: 'disappointed face', cat: 'Smileys & People' },
  { char: '😓', name: 'downcast face sweat', cat: 'Smileys & People' },
  { char: '😩', name: 'weary face', cat: 'Smileys & People' },
  { char: '😫', name: 'tired face', cat: 'Smileys & People' },
  { char: '🥱', name: 'yawning face', cat: 'Smileys & People' },
  { char: '😤', name: 'face steam nose', cat: 'Smileys & People' },
  { char: '😡', name: 'pouting face angry', cat: 'Smileys & People' },
  { char: '😠', name: 'angry face', cat: 'Smileys & People' },
  { char: '🤬', name: 'face symbols mouth angry swearing', cat: 'Smileys & People' },
  { char: '😈', name: 'smiling face horns devil', cat: 'Smileys & People' },
  { char: '👿', name: 'angry face horns devil', cat: 'Smileys & People' },
  { char: '💀', name: 'skull', cat: 'Smileys & People' },
  { char: '☠️', name: 'skull crossbones', cat: 'Smileys & People' },
  { char: '💩', name: 'pile of poo', cat: 'Smileys & People' },
  { char: '🤡', name: 'clown face', cat: 'Smileys & People' },
  { char: '👹', name: 'ogre', cat: 'Smileys & People' },
  { char: '👺', name: 'goblin', cat: 'Smileys & People' },
  { char: '👻', name: 'ghost', cat: 'Smileys & People' },
  { char: '👽', name: 'alien', cat: 'Smileys & People' },
  { char: '👾', name: 'alien monster', cat: 'Smileys & People' },
  { char: '🤖', name: 'robot', cat: 'Smileys & People' },
  { char: '👋', name: 'waving hand wave hi', cat: 'Smileys & People' },
  { char: '🤚', name: 'raised back of hand', cat: 'Smileys & People' },
  { char: '🖐️', name: 'hand splayed', cat: 'Smileys & People' },
  { char: '✋', name: 'raised hand stop', cat: 'Smileys & People' },
  { char: '🖖', name: 'vulcan salute', cat: 'Smileys & People' },
  { char: '👌', name: 'ok hand', cat: 'Smileys & People' },
  { char: '🤌', name: 'pinched fingers italian', cat: 'Smileys & People' },
  { char: '🤏', name: 'pinching hand small', cat: 'Smileys & People' },
  { char: '✌️', name: 'victory hand peace', cat: 'Smileys & People' },
  { char: '🤞', name: 'crossed fingers luck', cat: 'Smileys & People' },
  { char: '🤟', name: 'love you gesture', cat: 'Smileys & People' },
  { char: '🤘', name: 'sign of horns rock', cat: 'Smileys & People' },
  { char: '🤙', name: 'call me hand', cat: 'Smileys & People' },
  { char: '👈', name: 'backhand index pointing left', cat: 'Smileys & People' },
  { char: '👉', name: 'backhand index pointing right', cat: 'Smileys & People' },
  { char: '👆', name: 'backhand index pointing up', cat: 'Smileys & People' },
  { char: '👇', name: 'backhand index pointing down', cat: 'Smileys & People' },
  { char: '☝️', name: 'index pointing up', cat: 'Smileys & People' },
  { char: '👍', name: 'thumbs up like', cat: 'Smileys & People' },
  { char: '👎', name: 'thumbs down dislike', cat: 'Smileys & People' },
  { char: '✊', name: 'raised fist', cat: 'Smileys & People' },
  { char: '👊', name: 'oncoming fist punch', cat: 'Smileys & People' },
  { char: '🤛', name: 'left facing fist', cat: 'Smileys & People' },
  { char: '🤜', name: 'right facing fist', cat: 'Smileys & People' },
  { char: '👏', name: 'clapping hands clap', cat: 'Smileys & People' },
  { char: '🙌', name: 'raised hands celebrate', cat: 'Smileys & People' },
  { char: '👐', name: 'open hands', cat: 'Smileys & People' },
  { char: '🤲', name: 'palms up together', cat: 'Smileys & People' },
  { char: '🤝', name: 'handshake', cat: 'Smileys & People' },
  { char: '🙏', name: 'folded hands pray please thanks', cat: 'Smileys & People' },
  { char: '✍️', name: 'writing hand', cat: 'Smileys & People' },
  { char: '💅', name: 'nail polish', cat: 'Smileys & People' },
  { char: '🤳', name: 'selfie', cat: 'Smileys & People' },
  { char: '💪', name: 'flexed biceps muscle', cat: 'Smileys & People' },
  { char: '🦾', name: 'mechanical arm', cat: 'Smileys & People' },
  { char: '🦿', name: 'mechanical leg', cat: 'Smileys & People' },
  { char: '🦵', name: 'leg', cat: 'Smileys & People' },
  { char: '🦶', name: 'foot', cat: 'Smileys & People' },
  { char: '👂', name: 'ear', cat: 'Smileys & People' },
  { char: '🦻', name: 'ear hearing aid', cat: 'Smileys & People' },
  { char: '👃', name: 'nose', cat: 'Smileys & People' },
  { char: '🧠', name: 'brain', cat: 'Smileys & People' },
  { char: '🦷', name: 'tooth', cat: 'Smileys & People' },
  { char: '🦴', name: 'bone', cat: 'Smileys & People' },
  { char: '👀', name: 'eyes', cat: 'Smileys & People' },
  { char: '👁️', name: 'eye', cat: 'Smileys & People' },
  { char: '👅', name: 'tongue', cat: 'Smileys & People' },
  { char: '👄', name: 'mouth', cat: 'Smileys & People' },
  { char: '👶', name: 'baby', cat: 'Smileys & People' },
  { char: '🧒', name: 'child', cat: 'Smileys & People' },
  { char: '👦', name: 'boy', cat: 'Smileys & People' },
  { char: '👧', name: 'girl', cat: 'Smileys & People' },
  { char: '🧑', name: 'person', cat: 'Smileys & People' },
  { char: '👱', name: 'person blond hair', cat: 'Smileys & People' },
  { char: '👨', name: 'man', cat: 'Smileys & People' },
  { char: '🧔', name: 'person beard', cat: 'Smileys & People' },
  { char: '👩', name: 'woman', cat: 'Smileys & People' },
  { char: '🧓', name: 'older person', cat: 'Smileys & People' },
  { char: '👴', name: 'old man', cat: 'Smileys & People' },
  { char: '👵', name: 'old woman', cat: 'Smileys & People' }
];
