export const SYMBOLS_EMOJIS = [
  { char: '❤️', name: 'red heart love', cat: 'Symbols' },
  { char: '🧡', name: 'orange heart love', cat: 'Symbols' },
  { char: '💛', name: 'yellow heart love', cat: 'Symbols' },
  { char: '💚', name: 'green heart love', cat: 'Symbols' },
  { char: '💙', name: 'blue heart love', cat: 'Symbols' },
  { char: '💜', name: 'purple heart love', cat: 'Symbols' },
  { char: '🖤', name: 'black heart love', cat: 'Symbols' },
  { char: '🤍', name: 'white heart love', cat: 'Symbols' },
  { char: '🤎', name: 'brown heart love', cat: 'Symbols' },
  { char: '💔', name: 'broken heart sad love', cat: 'Symbols' },
  { char: '❣️', name: 'heart exclamation', cat: 'Symbols' },
  { char: '💕', name: 'two hearts love', cat: 'Symbols' },
  { char: '💞', name: 'revolving hearts love', cat: 'Symbols' },
  { char: '💓', name: 'beating heart love', cat: 'Symbols' },
  { char: '💗', name: 'growing heart love', cat: 'Symbols' },
  { char: '💖', name: 'sparkling heart love', cat: 'Symbols' },
  { char: '💘', name: 'heart with arrow love', cat: 'Symbols' },
  { char: '💝', name: 'heart with ribbon love', cat: 'Symbols' },
  { char: '💟', name: 'heart decoration love', cat: 'Symbols' },
  { char: '🔥', name: 'fire flame hot lit', cat: 'Symbols' },
  { char: '✨', name: 'sparkles sparkle shiny', cat: 'Symbols' },
  { char: '⭐', name: 'star gold', cat: 'Symbols' },
  { char: '🌟', name: 'glowing star', cat: 'Symbols' },
  { char: '⚡', name: 'high voltage lightning bolt', cat: 'Symbols' },
  { char: '🌈', name: 'rainbow', cat: 'Symbols' },
  { char: '☁️', name: 'cloud weather', cat: 'Symbols' },
  { char: '☀️', name: 'sun weather hot', cat: 'Symbols' },
  { char: '❄️', name: 'snowflake cold weather', cat: 'Symbols' },
  { char: '🎉', name: 'party popper celebrate', cat: 'Symbols' },
  { char: '🎁', name: 'gift present', cat: 'Symbols' },
  { char: '🎂', name: 'birthday cake', cat: 'Symbols' },
  { char: '🎈', name: 'balloon party', cat: 'Symbols' },
  { char: '🚀', name: 'rocket ship space', cat: 'Symbols' },
  { char: '🛸', name: 'flying saucer ufo space', cat: 'Symbols' },
  { char: '🎵', name: 'musical note music', cat: 'Symbols' },
  { char: '🎶', name: 'musical notes music', cat: 'Symbols' },
  { char: '💹', name: 'chart increasing with yen', cat: 'Symbols' },
  { char: '✅', name: 'check mark button', cat: 'Symbols' },
  { char: '✔️', name: 'check mark', cat: 'Symbols' },
  { char: '❌', name: 'cross mark x', cat: 'Symbols' },
  { char: '❎', name: 'cross mark button', cat: 'Symbols' },
  { char: '➕', name: 'plus sign', cat: 'Symbols' },
  { char: '➖', name: 'minus sign', cat: 'Symbols' },
  { char: '✖️', name: 'multiplication sign', cat: 'Symbols' },
  { char: '➗', name: 'division sign', cat: 'Symbols' },
  { char: '♾️', name: 'infinity', cat: 'Symbols' },
  { char: '❓', name: 'question mark', cat: 'Symbols' },
  { char: '❔', name: 'white question mark', cat: 'Symbols' },
  { char: '❕', name: 'white exclamation mark', cat: 'Symbols' },
  { char: '❗', name: 'exclamation mark', cat: 'Symbols' }
];
